- hosts: localhost

  tasks: 

    - name: Create the ELB listening port 80
      ec2_elb_lb:
         name: aws-elb-demo
         state: present
         region: us-west-2
         zones:
           -  us-west-2c
         listeners:
           - protocol: http
             load_balancer_port: 80
             instance_port: 80
      register: aws-elb-demo

    - name: Add the Mediawiki server's to the loadbalancer
      local_action: ec2_elb
      args:
        instance_id: "{{ item.id }}"
        ec2_elbs: aws-elb-demo
        state: present
        region: us-west-2
      with_items: '{{ec2.instances}}'

