---
- name: MediaWiki installation.
  hosts: all
  remote_user: centos
  sudo: yes

  tasks:

    - name: Install Apache
      shell: sudo yum install -y httpd 

    - name: Install php-intl
      shell: sudo yum install -y php-intl

    - name: Install php-gd
      shell: sudo yum install -y php-gd

    - name: Install texlive
      shell: sudo yum install -y texlive

    - name: Install epel-release
      shell: sudo yum install -y epel-release

    - name: Install php
      shell: sudo yum install -y php

    - name: Install php-mysql
      shell: sudo yum install -y php-mysql

    - name: Selinux config
      replace:
        name: /etc/selinux/config
        regexp: 'enforcing'
        replace: 'disabled'
     
    - name: Download MediaWiki
      get_url: url=http://releases.wikimedia.org/mediawiki/1.24/mediawiki-1.24.1.tar.gz dest=/home/centos/mediawiki-1.24.1.tar.gz mode=0777 force=no

    - name: Untar MediaWiki
      shell: tar xvzf mediawiki-*.tar.gz

    - name: Move the file
      shell: sudo mv mediawiki-1.24.1/* /var/www/html

    - name: Service Restart
      shell: sudo systemctl restart httpd

